In [11]:
# NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
# Below is a list of all data types in NumPy and the characters used to represent them.
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

In [12]:
# checking data types in python
import numpy as np
arr = np.array([1, 2, 3, 4])
arr1= np.array(['apple', 'banana', 'cherry'])
print(arr1.dtype)  
print(arr.dtype)

<U6
int64


In [26]:
# We cas also change the data type of an array
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr.dtype) 

arr = np.array([1, 2, 3, 4], dtype='i1')
print(arr.dtype) 

arr = np.array([1, 2, 3, 4], dtype='i2')
print(arr.dtype) 

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr.dtype) 

arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr.dtype) 

arr = np.array([1, 2, 3, 4], dtype='i')
print(arr.dtype) 

arr = np.array([1, 2, 3, 4], dtype='u1')
print(arr.dtype) 

arr = np.array([1, 2, 3, 4], dtype='u2')
print(arr.dtype) 

arr = np.array([1, 2, 3, 4], dtype='u4')
print(arr.dtype) 

arr = np.array([1, 2, 3, 4], dtype='u8')
print(arr.dtype) 



# Change data type of array
arr = np.array([1, 2, 3, 4])
newarr = arr.astype('f')
print(newarr)
print(newarr.dtype)


|S1
int8
int16
int32
int64
int32
uint8
uint16
uint32
uint64
[1. 2. 3. 4.]
float32


In [20]:
# Make a copy, change the original array, and display both arrays:
import numpy as np
arr1= np.array([1, 2, 3, 4])
arr2= arr1.copy()
arr3=arr2.view()
arr1[0]=10
arr1[0] = 42
print(arr1)
print(arr2)

[42  2  3  4]
[1 2 3 4]


Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [21]:
import numpy as np
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8],[41,56,85,96]],[[1, 2, 3, 4], [5, 6, 7, 8],[15,63,6,1]],[[1, 2, 3, 4], [5, 6, 7, 8],[1,2,3,4]]])
print(arr.shape)

# reshaping the array
arr2=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,526,3,64,6,3,5,2,96,3,4,85,4,52,96,9,6,4,5,41])
a=len(arr2)
print(a)
arr1=arr2.reshape(4,7)
print(arr1)

(3, 3, 4)
28
[[  1   2   3   4   5   6   7]
 [  8   9 526   3  64   6   3]
 [  5   2  96   3   4  85   4]
 [ 52  96   9   6   4   5  41]]


In [22]:
# iteration through the array
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [23]:
# Attributes of array

# 1. size = total element
# 2. Dimensions = 1-D, 2-D
# 3. shape = (rows,columns)
# 4. dataType = int,float,etc.
# 5. itemsize =

import numpy as np

arr = np.array([[10, 20, 3000], [40, 50, 60]])
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)


# 3-D Array
arr_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3D)
print(arr_3D.ndim)
print(arr_3D.shape)
print(arr_3D.size)
print(arr_3D.dtype)
print(arr_3D.itemsize)

6
(2, 3)
2
int64
8
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8
int64
8


In [24]:
# Adding the element list from other list
import numpy as np
list1 = [1, 2, 3, 4, 5]
list2 = [10, 20, 30, 40, 50]
return_list = []
for i in range(len(list1)):
    return_list.append(list1[i] + list2[i])
print(return_list)

arr1= np.array([1, 2, 3, 4, 5])
arr2= np.array([10, 20, 30, 40, 50])
arr3= arr1+arr2
print(arr3)

import time
list1 = range(1000000)
list2 = range(1000000)
start_time = time.time()
result = [(x + y) for x, y in zip(list1, list2)]
print("Time taken by list operation: ", (time.time() - start_time))


arr1 = np.arange(1000000)
arr2 = np.arange(1000000)
start_time = time.time()
arr3 = arr1 + arr2
end= time.time()
print("Time taken by numpy operation: ", (end-start_time))

[11, 22, 33, 44, 55]
[11 22 33 44 55]
Time taken by list operation:  0.13809967041015625
Time taken by numpy operation:  0.014583587646484375
