In [5]:
# Operation in numpy

import numpy as np
arr = np.array([1, 2, 3, 4])
newarr = arr.astype('f')
print(newarr)
print(newarr.dtype)

# Copy and view
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.copy())
print(arr.view())

# Array with random values
arr = np.random.randint(10, size=(3, 3))
print(arr)

# Array with random values
arr = np.random.rand(3, 3)
print(arr)

# Array with random values
arr = np.random.randn(3, 3)
print(arr)


[1. 2. 3. 4.]
float32
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[[1 8 0]
 [7 3 7]
 [9 2 0]]
[[0.76381795 0.22372681 0.97836924]
 [0.97993894 0.5411349  0.3645753 ]
 [0.99171751 0.71733726 0.12089318]]
[[-0.45375517  0.59392043 -0.24084066]
 [ 0.05214389  0.43814811 -0.43426302]
 [ 0.36425967  0.60390654 -0.05298465]]


In [ ]:
# Addition of arrays
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(arr1 + arr2)

# Subtraction of arrays
print(arr1 - arr2)

# Multiplication of arrays
print(arr1 * arr2)

# Division of arrays 
print(arr1 / arr2)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
