In [2]:
import numpy as np
# Problem in List then come Numpy

tempreature=[32.6,35.6,34.9,36.6]
toatl=0
for temp in tempreature:
    toatl+=temp
    
avrage_temp=toatl/len(tempreature)
print(avrage_temp)



34.925


In [4]:

import numpy as np

tempreture=[32.6,35.6,34.9,36.6]
tempreture_array=np.array(tempreature)
avrage_temp=np.average(tempreture_array)
print(avrage_temp)

34.925


In [6]:
#  That use large datasets

python_list=[1,2,3,4,5,6,7,8,9,10]
print(python_list)

numpy_array=np.array([1,2,3,4,5,6,7,8,9,10])
print(numpy_array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# Multi-dimentional array

# Metrices

metrices=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(metrices)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Multi-dimentional array
# With defualt value array
#  with zeros(shape)
numpy_array=np.zeros((3,3))
print(numpy_array)
numpy_array=np.zeros((3,3))
print(numpy_array)
numpy_array=np.zeros((4,3))
print(numpy_array)
numpy_array=np.zeros((3,4))
print(numpy_array)
numpy_array=np.zeros((5,5))
print(numpy_array)
numpy_array=np.zeros((6,6))
print(numpy_array)
numpy_array=np.zeros((7,7))
print(numpy_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [14]:
# defualt value array

metrices=np.ones((3,3))
print(metrices)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
# Default value array

metrices=np.full((3,3),5)
print(metrices)

# identity matrix
print("identity matrix")
metrices=np.identity(3)
print(metrices)


metrices=np.eye(3)
print("eye matrix")
print(metrices)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
eye matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# arange array
# Arange is used to create an array with a range of values
# arange(start,stop,step)
array=np.arange(12,50,2)
print(array)




[12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
