In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# Creating 2D array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
# Creating 3D array
print("Creating 3D array")
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
# creating 4-d array
import numpy as np
print("Creating 4D array")
arr4=np.array([[[[2,5,6,3,9,3,1,20,3,20,63],[2,5,6,3,9,3,1,20,3,20,63],[2,5,6,3,9,3,1,20,3,20,63]],[[2,5,6,3,9,3,1,20,3,20,63],[2,5,6,3,9,3,1,20,3,20,63],[2,5,6,3,9,3,1,20,3,20,63]]]])
print(arr4)

Creating 4D array
[[[[ 2  5  6  3  9  3  1 20  3 20 63]
   [ 2  5  6  3  9  3  1 20  3 20 63]
   [ 2  5  6  3  9  3  1 20  3 20 63]]

  [[ 2  5  6  3  9  3  1 20  3 20 63]
   [ 2  5  6  3  9  3  1 20  3 20 63]
   [ 2  5  6  3  9  3  1 20  3 20 63]]]]


In [13]:
import numpy as np
print("User input array")
num=int(input("Enter size of array:"))
a=[]
for i in range(num):
    a.append(int(input(f"Enter number for {i+1} index:")))
a=np.array(a)
print(a)

User input array


ValueError: invalid literal for int() with base 10: ''