In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# Creating 2D array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
# Creating 3D array
print("Creating 3D array")
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
# creating 4-d array
import numpy as np
print("Creating 4D array")
arr4=np.array([[[[2,5,6,3,9,3,1,20,3,20,63],[2,5,6,3,9,3,1,20,3,20,63],[2,5,6,3,9,3,1,20,3,20,63]],[[2,5,6,3,9,3,1,20,3,20,63],[2,5,6,3,9,3,1,20,3,20,63],[2,5,6,3,9,3,1,20,3,20,63]]]])
print(arr4)

Creating 4D array
[[[[ 2  5  6  3  9  3  1 20  3 20 63]
   [ 2  5  6  3  9  3  1 20  3 20 63]
   [ 2  5  6  3  9  3  1 20  3 20 63]]

  [[ 2  5  6  3  9  3  1 20  3 20 63]
   [ 2  5  6  3  9  3  1 20  3 20 63]
   [ 2  5  6  3  9  3  1 20  3 20 63]]]]


In [1]:
import numpy as np
print("User input array")
num=int(input("Enter size of array:"))
a=[]
for i in range(num):
    a.append(int(input(f"Enter number for {i+1} index:")))
a=np.array(a)
print(a)

User input array
[12 23 63 65 21]


In [2]:
# User input 2D array
import numpy as np
print("User input 2D array")
row=int(input("Enter number of rows:"))
col=int(input("Enter number of columns:"))
a=[]
for i in range(row):
    a.append([])
    for j in range(col):
        a[i].append(int(input(f"Enter number for {i+1} row and {j+1} column:")))
a=np.array(a)
print(a)
print(a.ndim)

User input 2D array
[[12 13]
 [25 36]]
2


In [3]:
# check version of numpy
import numpy as np
print(np.__version__)

2.2.2


In [12]:
# Accessing elements of array
import numpy as np
a=np.array([1,2,3,4,5])
print(a[0])
print(a[1])
print(a[2])

# 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print("there is given first row first element of array is= ",arr2[0][0])
print("there is given Second row third element of array is= ",arr2[1][2])

1
2
3
there is given first row first element of array is=  1
there is given Second row third element of array is=  6


In [20]:
# Create a 3d array and access the elements
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[ 1,2,3],[4,5,6]]])
print(a[0][0][0])
#4d array
arr=np.array([[[[12,63,63,98,2,3],[2,60,3,9,2,13],[4,600,3,63,2,4]],[[12,63,63,98,2,3],[12,63,63,98,2,3],[12,63,63,98,2,3]]]])
print(arr)
print(arr[0][0][0][0])
print(arr[0][0][2][1])

1
[[[[ 12  63  63  98   2   3]
   [  2  60   3   9   2  13]
   [  4 600   3  63   2   4]]

  [[ 12  63  63  98   2   3]
   [ 12  63  63  98   2   3]
   [ 12  63  63  98   2   3]]]]
12
600


In [23]:
# Slicing of array
# We pass slice instead of index like this: [start:end].
# We can also define the step, like this: [start:end:step].
# If we don't pass start its considered 0
# If we don't pass end its considered length of array in that dimension
# If we don't pass step its considered 1
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[1:5])
print(a[1:])
print(a[:5])

[2 3 4 5]
[2 3 4 5 6 7 8 9]
[1 2 3 4 5]
